spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: taolao123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shinyjewelry39@gmail.com
    password: juxx vpev tszm nrlf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
server:
  port: 8089

jwt:
  access:
    secret: mysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff
    expire: 1
  refresh:
    secret: myrefreshsecretkeymysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff
    expire: 7

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
