version: "3.9"

services:
  cart-service:
    build:
        context: ./cart
        dockerfile: Dockerfile
    container_name: cart-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cart_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

  course-service:
    build:
        context: ./course
        dockerfile: Dockerfile
    container_name: course-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/course_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

  discovery-service:
    build:
        context: ./discovery
        dockerfile: Dockerfile
    container_name: discovery-service
    networks:
        - cinx-network

  learning-service:
    build:
        context: ./learning
        dockerfile: Dockerfile
    container_name: learning-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/learning_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

  media-service:
    build:
        context: ./media
        dockerfile: Dockerfile
    container_name: media-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/media_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

  notification-service:
    build:
        context: ./notification
        dockerfile: Dockerfile
    container_name: notification-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notification_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

  payment-service:
    build:
        context: ./payment
        dockerfile: Dockerfile
    container_name: payment-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

  social-service:
    build:
        context: ./social
        dockerfile: Dockerfile
    container_name: social-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/social_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

  user-service:
    build:
        context: ./user
        dockerfile: Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
        - cinx-network

networks:
  cinx-network:
    driver: bridge
    name: cinx-network
