spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8086
jwt:
  access:
    expire: 1
  refresh:
    expire: 7
firebase:
  config-path: ./cinx-d9301-72bfc680e59c.json
