{
 "title": "CINX - API Gateway Observability",
 "tags": [
  "spring-cloud",
  "gateway",
  "cinx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Gateway Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count[5m])) by (routeId)",
     "legendFormat": "Route: {{routeId}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_sum[5m])) by (routeId) / sum(rate(spring_cloud_gateway_requests_seconds_count[5m])) by (routeId)",
     "legendFormat": "Route: {{routeId}}"
    }
   ]
  },
  {
   "title": "Errors by Status Code (Gateway & Routes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{status=~\"5..\"}[5m])) by (routeId, status)",
     "legendFormat": "Route: {{routeId}} (Status: {{status}})"
    }
   ]
  }
 ]
}