{
 "title": "CINX - RabbitMQ Observability",
 "tags": [
  "rabbitmq",
  "amqp",
  "cinx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Messages in Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages) by (queue)",
     "legendFormat": "Queue: {{queue}}"
    }
   ]
  },
  {
   "title": "Queue Consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_consumers) by (queue)",
     "legendFormat": "Queue: {{queue}}"
    }
   ]
  },
  {
   "title": "RabbitMQ Broker Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_process_resident_memory_bytes",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "rabbitmq_resident_memory_limit_bytes",
     "legendFormat": "Memory Limit"
    }
   ]
  }
 ]
}