spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth
              predicates:
                - Path=/api/v1/auth/**
            - id: cart-service
              uri: lb://cart
              predicates:
                - Path=/api/v1/cart/**
            - id: discovery-service
              uri: lb://discovery
              predicates:
                - Path=/api/v1/discovery/**
            - id: user-service
              uri: lb://user
              predicates:
                - Path=/api/v1/users/**
            - id: course-service
              uri: lb://course
              predicates:
                - Path=/api/v1/courses/**,/api/v1/categories/**
            - id: enrollment-service
              uri: lb://enrollment
              predicates:
                - Path=/api/v1/enrollments/**, /api/v1/orders/**
            - id: payment-service
              uri: lb://payment
              predicates:
                - Path=/api/v1/payments/**
            - id: learning-service
              uri: lb://learning
              predicates:
                - Path=/api/v1/learning/**
            - id: notification-service
              uri: lb://notification
              predicates:
                - Path=/api/v1/notifications/**
            - id: notification-websocket
              uri: lb:ws://notification
              predicates:
                - Path=/ws/notifications/**
            - id: social-service
              uri: lb://social
              predicates:
                - Path=/api/v1/wishlist/**, /api/v1/reviews/**

server:
    port: 9090

jwt:
  access:
    secret: mysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff
    expire: 1