spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/cinx
    username: root
    password: taolao123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shinyjewelry39@gmail.com
    password: juxx vpev tszm nrlf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8888

jwt:
  access:
    secret: mysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff
    expire: 1
  refresh:
    secret: myrefreshsecretkeymysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff
    expire: 7