spring:
  application:
    name: auth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:taolao123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:iamkvnn.cinehub@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:bqfg xerx gfaw bcrb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8888

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:mysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 1
  refresh:
    secret: ${JWT_REFRESH_SECRET:myrefreshsecretkeymysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 7

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

google:
  token-uri: ${GOOGLE_TOKEN_URI:https://oauth2.googleapis.com/token}
  mobile-redirect-uri: ${GOOGLE_MOBILE_REDIRECT_URI:com.example.app:/oauth2redirect}
  web-redirect-uri: ${GOOGLE_WEB_REDIRECT_URI:http://localhost:5173/oauth2/callback}
  user-info-uri: ${GOOGLE_USER_INFO_URL:https://www.googleapis.com/oauth2/v3/userinfo}
  client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}

gateway.url: ${GATEWAY_URL:http://localhost:9090}

aws:
  region: ${AWS_REGION:ap-southeast-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket: ${AWS_S3_BUCKET:cinx-dev}
    endpoint: ${AWS_S3_ENDPOINT:https://s3.ap-southeast-1.amazonaws.com}
