spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/cinx
    username: root
    password: taolao123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
    port: 8888