spring:
  application:
    name: payment
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:taolao123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000

server:
  port: 8087

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:mysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 1
  refresh:
    secret: ${JWT_REFRESH_SECRET:myrefreshsecretkeymysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 7

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

VNPay:
  vnp_Version: 2.1.0
  vnp_Command: pay
  vnp_TmnCode: ${VNPAY_TMN_CODE:YAECLV2E}
  vnp_HashSecret: ${VNPAY_HASH_SECRET:XWQ7OO6P3LE601JZGCMIC6HM4AU4EAB0}
  vnp_Url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

MoMo:
  returnUrl: ${MOMO_RETURN_URL:https://shinyjewelry.shop/payment/momo-return}
  notifyUrl: ${MOMO_NOTIFY_URL:https://api.shinyjewelry.shop/api/v1/payments/momo-callback}
  url: https://test-payment.momo.vn/v2/gateway/api/create
  partnerCode: ${MOMO_PARTNER_CODE:MOMOBKUN20180529}
  accessKey: ${MOMO_ACCESS_KEY:klm05TvNBzhg7h7j}
  secret: ${MOMO_SECRET:at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa}

feBaseUrl: ${FE_BASE_URL:https://shinyjewelry.shop}