spring:
  application:
    name: payment
  rabbitmq:
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
server:
  port: 8087
jwt:
  access:
    expire: 1
  refresh:
    expire: 7
VNPay:
  vnp_Version: 2.1.0
  vnp_Command: pay
  vnp_Url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
MoMo:
  url: https://test-payment.momo.vn/v2/gateway/api/create
