spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
gateway.url: ${GATEWAY_URL}
