spring:
  application:
    name: enrollment
  rabbitmq:
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
server:
  port: 8085
jwt:
  access:
    expire: 1
  refresh:
    expire: 7
