spring:
  application:
    name: course
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/coursedb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:taolao123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:mysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 1
  refresh:
    secret: ${JWT_REFRESH_SECRET:myrefreshsecretkeymysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 7

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dxjusps3n}
  api-key: ${CLOUDINARY_API_KEY:268928962386637}
  api-secret: ${CLOUDINARY_API_SECRET:9E91Uo7DXxRZrH9YA5payyyKYk0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

server:
  port: 8081

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:https://s3.amazonaws.com}
    cdn-url: ${AWS_S3_CDN_URL:cdn}
    bucket: ${AWS_S3_BUCKET:bucket}
  region: ${AWS_REGION:us-east-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY:key}
    secret-key: ${AWS_SECRET_KEY:secret}
gateway.url: ${GATEWAY_URL:http://localhost:9090}
