spring:
  application:
    name: learning
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/learningdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:taolao123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:mysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 1
  refresh:
    secret: ${JWT_REFRESH_SECRET:myrefreshsecretkeymysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffffmysecretkeygfhfffffffffffffffffffffffffffffffffffff}
    expire: 7

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:endpoint}
    cdn-url: ${AWS_S3_CDN_URL:cdn}
    bucket: ${AWS_S3_BUCKET:bucket}
  region: ${AWS_REGION:us-east-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY:key}
    secret-key: ${AWS_SECRET_KEY:secret}