spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT}
    cdn-url: ${AWS_S3_CDN_URL}
    bucket: ${AWS_S3_BUCKET}
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
gateway.url: ${GATEWAY_URL}
