name: Cart Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "cart/**"
      - "common/**" # rebuild if common lib changes
      - "pom.xml"
      - ".github/workflows/cart-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "cart/**"
      - "common/**"
      - "pom.xml"
      - ".github/workflows/cart-ci.yml"
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -pl cart -am -DskipTests

      - name: Run Tests
        run: mvn test -pl cart

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: ./cart
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cinx-cart:latest

