name: Gateway Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "gateway/**"
      - "common/**"
      - "pom.xml"
      - ".github/workflows/gateway-ci.yml"
      - ".github/workflows/gateway-cd.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "gateway/**"
      - "common/**"
      - "pom.xml"
      - ".github/workflows/gateway-ci.yml"
      - ".github/workflows/gateway-cd.yml"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -pl gateway -am -DskipTests
